// <auto-generated />
using System;
using FitVerse.Web.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitVerse.Web.Migrations
{
    [DbContext(typeof(FitVerseContext))]
    [Migration("20250613180640_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitVerse.Web.Models.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Banners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 12, 17, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Up to 50% off on summer collection",
                            DisplayOrder = 1,
                            ImageUrl = "/images/banners/slider1.jpg",
                            IsActive = true,
                            LinkUrl = "/Product/CategoryProducts?categoryId=12",
                            Title = "Summer Sale",
                            UpdatedAt = new DateTime(2022, 12, 17, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 12, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Check out our latest fashion trends",
                            DisplayOrder = 2,
                            ImageUrl = "/images/banners/slider2.jpg",
                            IsActive = true,
                            LinkUrl = "/Home/Index",
                            Title = "New Arrivals",
                            UpdatedAt = new DateTime(2022, 12, 18, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 12, 19, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stay warm with our winter essentials",
                            DisplayOrder = 3,
                            ImageUrl = "/images/banners/slider3.jpg",
                            IsActive = true,
                            LinkUrl = "/Product/CategoryProducts?categoryId=6",
                            Title = "Winter Collection",
                            UpdatedAt = new DateTime(2022, 12, 19, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FitVerse.Web.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 1,
                            Quantity = 2,
                            UpdatedAt = new DateTime(2023, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 1, 1, 11, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 3,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2023, 1, 1, 11, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 6,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2023, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 8,
                            Quantity = 2,
                            UpdatedAt = new DateTime(2023, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("FitVerse.Web.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Men's Clothing",
                            ImageUrl = "/images/categories/men.jpg",
                            IsActive = true,
                            Name = "Men",
                            UpdatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Women's Clothing",
                            ImageUrl = "/images/categories/women.jpg",
                            IsActive = true,
                            Name = "Women",
                            UpdatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kids' Clothing",
                            ImageUrl = "/images/categories/kids.jpg",
                            IsActive = true,
                            Name = "Kids",
                            UpdatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fashion Accessories",
                            ImageUrl = "/images/categories/accessories.jpg",
                            IsActive = true,
                            Name = "Accessories",
                            UpdatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Men's T-Shirts",
                            ImageUrl = "/images/categories/men/t-shirts.jpg",
                            IsActive = true,
                            Name = "T-Shirts",
                            ParentCategoryId = 1,
                            UpdatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Men's Jackets",
                            ImageUrl = "/images/categories/men/jackets.jpg",
                            IsActive = true,
                            Name = "Jackets",
                            ParentCategoryId = 1,
                            UpdatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Men's Sweatshirts",
                            ImageUrl = "/images/categories/men/sweatshirts.jpg",
                            IsActive = true,
                            Name = "Sweatshirts",
                            ParentCategoryId = 1,
                            UpdatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Men's Shirts",
                            ImageUrl = "/images/categories/men/shirts.jpg",
                            IsActive = true,
                            Name = "Shirts",
                            ParentCategoryId = 1,
                            UpdatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Men's Pullovers",
                            ImageUrl = "/images/categories/men/pullovers.jpg",
                            IsActive = true,
                            Name = "Pullovers",
                            ParentCategoryId = 1,
                            UpdatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Men's Pants",
                            ImageUrl = "/images/categories/men/pants.jpg",
                            IsActive = true,
                            Name = "Pants",
                            ParentCategoryId = 1,
                            UpdatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Men's Shorts",
                            ImageUrl = "/images/categories/men/shorts.jpg",
                            IsActive = true,
                            Name = "Shorts",
                            ParentCategoryId = 1,
                            UpdatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Women's T-Shirts",
                            ImageUrl = "/images/categories/women/t-shirts.jpg",
                            IsActive = true,
                            Name = "T-Shirts",
                            ParentCategoryId = 2,
                            UpdatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Women's Jackets",
                            ImageUrl = "/images/categories/women/jackets.jpg",
                            IsActive = true,
                            Name = "Jackets",
                            ParentCategoryId = 2,
                            UpdatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Women's Sweatshirts",
                            ImageUrl = "/images/categories/women/sweatshirts.jpg",
                            IsActive = true,
                            Name = "Sweatshirts",
                            ParentCategoryId = 2,
                            UpdatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Women's Shirts & Blouses",
                            ImageUrl = "/images/categories/women/shirts-blouses.jpg",
                            IsActive = true,
                            Name = "Shirts & Blouses",
                            ParentCategoryId = 2,
                            UpdatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Women's Pullovers",
                            ImageUrl = "/images/categories/women/pullovers.jpg",
                            IsActive = true,
                            Name = "Pullovers",
                            ParentCategoryId = 2,
                            UpdatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Women's Cardigans",
                            ImageUrl = "/images/categories/women/cardigans.jpg",
                            IsActive = true,
                            Name = "Cardigans",
                            ParentCategoryId = 2,
                            UpdatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Women's Sets & Dresses",
                            ImageUrl = "/images/categories/women/sets-dresses.jpg",
                            IsActive = true,
                            Name = "Sets & Dresses",
                            ParentCategoryId = 2,
                            UpdatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Women's Pants",
                            ImageUrl = "/images/categories/women/pants.jpg",
                            IsActive = true,
                            Name = "Pants",
                            ParentCategoryId = 2,
                            UpdatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Women's Skirts",
                            ImageUrl = "/images/categories/women/skirts.jpg",
                            IsActive = true,
                            Name = "Skirts",
                            ParentCategoryId = 2,
                            UpdatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Women's Home-wear",
                            ImageUrl = "/images/categories/women/home-wear.jpg",
                            IsActive = true,
                            Name = "Home-wear",
                            ParentCategoryId = 2,
                            UpdatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Boys' Clothing",
                            ImageUrl = "/images/categories/kids/boys.jpg",
                            IsActive = true,
                            Name = "Boys",
                            ParentCategoryId = 3,
                            UpdatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Girls' Clothing",
                            ImageUrl = "/images/categories/kids/girls.jpg",
                            IsActive = true,
                            Name = "Girls",
                            ParentCategoryId = 3,
                            UpdatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fashion Bags",
                            ImageUrl = "/images/categories/accessories/bags.jpg",
                            IsActive = true,
                            Name = "Bags",
                            ParentCategoryId = 4,
                            UpdatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fashion Belts",
                            ImageUrl = "/images/categories/accessories/belts.jpg",
                            IsActive = true,
                            Name = "Belts",
                            ParentCategoryId = 4,
                            UpdatedAt = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FitVerse.Web.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("date");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 12, 22, 12, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "test1@example.com",
                            CustomerName = "Test User One",
                            CustomerPhone = "555-111-2222",
                            OrderDate = new DateTime(2022, 12, 22, 12, 0, 0, 0, DateTimeKind.Utc),
                            ShippingAddress = "123 Main St, Anytown, Anystate 12345",
                            Status = "Delivered",
                            TotalAmount = 100.000m,
                            UpdatedAt = new DateTime(2022, 12, 27, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 12, 29, 12, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "test1@example.com",
                            CustomerName = "Test User One",
                            CustomerPhone = "555-111-2222",
                            OrderDate = new DateTime(2022, 12, 29, 12, 0, 0, 0, DateTimeKind.Utc),
                            ShippingAddress = "123 Main St, Anytown, Anystate 12345",
                            Status = "Shipped",
                            TotalAmount = 187.5000m,
                            UpdatedAt = new DateTime(2022, 12, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 12, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "test2@example.com",
                            CustomerName = "Test User Two",
                            CustomerPhone = "555-333-4444",
                            OrderDate = new DateTime(2022, 12, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            ShippingAddress = "456 Oak Ave, Villageton, Stateland 67890",
                            Status = "Pending",
                            TotalAmount = 132.7500m,
                            UpdatedAt = new DateTime(2022, 12, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("FitVerse.Web.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 12, 22, 12, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 2,
                            UnitPrice = 20.000m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 12, 22, 12, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = 1,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 60.00m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 12, 29, 12, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = 2,
                            ProductId = 10,
                            Quantity = 1,
                            UnitPrice = 60.000m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 12, 29, 12, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = 2,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 127.5000m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 12, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = 3,
                            ProductId = 6,
                            Quantity = 1,
                            UnitPrice = 33.7500m
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 12, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = 3,
                            ProductId = 8,
                            Quantity = 2,
                            UnitPrice = 49.500m
                        });
                });

            modelBuilder.Entity("FitVerse.Web.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNewArrival")
                        .HasColumnType("bit");

                    b.Property<string>("Material")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IsNewArrival");

                    b.HasIndex("Name");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2022, 12, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comfortable and stylish casual t-shirt for men. Perfect for everyday wear.",
                            DiscountPercentage = 20m,
                            ImageUrl = "/images/products/men/t-shirts/men-tshirt1.jpg",
                            IsActive = true,
                            IsNewArrival = true,
                            Material = "Cotton",
                            Name = "Men's Casual T-Shirt",
                            Price = 25.00m,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2022, 12, 12, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2022, 12, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium leather jacket for a bold look. Durable and fashionable.",
                            DiscountPercentage = 15m,
                            ImageUrl = "/images/products/men/jackets/men-jacket1.jpg",
                            IsActive = true,
                            IsNewArrival = false,
                            Material = "Leather",
                            Name = "Stylish Leather Jacket",
                            Price = 150.00m,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2022, 12, 7, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 18,
                            CreatedAt = new DateTime(2022, 12, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Light and airy summer dress, ideal for warm weather and special occasions.",
                            ImageUrl = "/images/products/women/sets-dresses/women-dress1.jpg",
                            IsActive = true,
                            IsNewArrival = true,
                            Material = "Polyester",
                            Name = "Elegant Summer Dress",
                            Price = 60.00m,
                            StockQuantity = 30,
                            UpdatedAt = new DateTime(2022, 12, 14, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 22,
                            CreatedAt = new DateTime(2022, 12, 16, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fun graphic t-shirt for boys, soft and breathable.",
                            DiscountPercentage = 10m,
                            ImageUrl = "/images/products/kids/boys/kids-boys-tee1.jpg",
                            IsActive = true,
                            IsNewArrival = true,
                            Material = "Cotton Blend",
                            Name = "Kids' Graphic Tee",
                            Price = 18.00m,
                            StockQuantity = 70,
                            UpdatedAt = new DateTime(2022, 12, 16, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 24,
                            CreatedAt = new DateTime(2022, 12, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chic handbag with multiple compartments, perfect for daily use.",
                            ImageUrl = "/images/products/accessories/bags/accessories-bag1.jpg",
                            IsActive = true,
                            IsNewArrival = false,
                            Material = "Synthetic Leather",
                            Name = "Designer Handbag",
                            Price = 85.00m,
                            StockQuantity = 40,
                            UpdatedAt = new DateTime(2022, 12, 10, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2022, 12, 13, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic denim shirt for a rugged yet stylish look. Versatile for any season.",
                            DiscountPercentage = 25m,
                            ImageUrl = "/images/products/men/shirts/men-shirt1.jpg",
                            IsActive = true,
                            IsNewArrival = false,
                            Material = "Denim",
                            Name = "Men's Denim Shirt",
                            Price = 45.00m,
                            StockQuantity = 60,
                            UpdatedAt = new DateTime(2022, 12, 13, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 20,
                            CreatedAt = new DateTime(2022, 12, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Flowy midi skirt with a vibrant floral print. Perfect for spring and summer.",
                            ImageUrl = "/images/products/women/skirts/women-skirt1.jpg",
                            IsActive = true,
                            IsNewArrival = true,
                            Material = "Viscose",
                            Name = "Women's Floral Skirt",
                            Price = 35.00m,
                            StockQuantity = 55,
                            UpdatedAt = new DateTime(2022, 12, 15, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2022, 12, 17, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Soft and warm hoodie, suitable for both men and women. Great for layering.",
                            DiscountPercentage = 10m,
                            ImageUrl = "/images/products/men/sweatshirts/unisex-hoodie1.jpg",
                            IsActive = true,
                            IsNewArrival = true,
                            Material = "Fleece",
                            Name = "Unisex Fleece Hoodie",
                            Price = 55.00m,
                            StockQuantity = 45,
                            UpdatedAt = new DateTime(2022, 12, 17, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 22,
                            CreatedAt = new DateTime(2022, 12, 9, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Durable and warm jacket for kids, ideal for cold weather adventures.",
                            ImageUrl = "/images/products/kids/boys/kids-jacket1.jpg",
                            IsActive = true,
                            IsNewArrival = false,
                            Material = "Waterproof Nylon",
                            Name = "Kids' Winter Jacket",
                            Price = 70.00m,
                            StockQuantity = 25,
                            UpdatedAt = new DateTime(2022, 12, 9, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 15,
                            CreatedAt = new DateTime(2022, 12, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Luxurious silk blouse, perfect for professional or formal occasions.",
                            DiscountPercentage = 20m,
                            ImageUrl = "/images/products/women/shirts-blouses/women-blouse1.jpg",
                            IsActive = true,
                            IsNewArrival = false,
                            Material = "Silk",
                            Name = "Elegant Women's Blouse",
                            Price = 75.00m,
                            StockQuantity = 35,
                            UpdatedAt = new DateTime(2022, 12, 11, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2022, 12, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Modern slim fit chino pants, comfortable and stylish for various occasions.",
                            ImageUrl = "/images/products/men/pants/men-pants1.jpg",
                            IsActive = true,
                            IsNewArrival = true,
                            Material = "Cotton Twill",
                            Name = "Men's Slim Fit Chinos",
                            Price = 50.00m,
                            StockQuantity = 65,
                            UpdatedAt = new DateTime(2022, 12, 18, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 25,
                            CreatedAt = new DateTime(2022, 12, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A timeless accessory, made from genuine leather for durability and style.",
                            ImageUrl = "/images/products/accessories/belts/accessories-belt1.jpg",
                            IsActive = true,
                            IsNewArrival = true,
                            Material = "Genuine Leather",
                            Name = "Classic Leather Belt",
                            Price = 30.00m,
                            StockQuantity = 80,
                            UpdatedAt = new DateTime(2022, 12, 20, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 19,
                            CreatedAt = new DateTime(2022, 12, 21, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-waist, comfortable yoga pants for all workouts.",
                            DiscountPercentage = 5m,
                            ImageUrl = "/images/products/women/pants/women-yogapants.jpg",
                            IsActive = true,
                            IsNewArrival = true,
                            Material = "Spandex Blend",
                            Name = "Women's Yoga Pants",
                            Price = 40.00m,
                            StockQuantity = 90,
                            UpdatedAt = new DateTime(2022, 12, 21, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 23,
                            CreatedAt = new DateTime(2022, 12, 23, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Soft and fun hoodie with popular character print for kids.",
                            ImageUrl = "/images/products/kids/girls/kids-hoodie.jpg",
                            IsActive = true,
                            IsNewArrival = false,
                            Material = "Cotton Fleece",
                            Name = "Kids' Character Hoodie",
                            Price = 30.00m,
                            StockQuantity = 110,
                            UpdatedAt = new DateTime(2022, 12, 23, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2022, 12, 24, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Breathable and quick-dry shorts for sports and casual wear.",
                            DiscountPercentage = 10m,
                            ImageUrl = "/images/products/men/shorts/men-shorts1.jpg",
                            IsActive = true,
                            IsNewArrival = true,
                            Material = "Polyester",
                            Name = "Men's Athletic Shorts",
                            Price = 22.00m,
                            StockQuantity = 150,
                            UpdatedAt = new DateTime(2022, 12, 24, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FitVerse.Web.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 12, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "test1@example.com",
                            FullName = "Test User One",
                            PasswordHash = "ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f",
                            Role = "Customer",
                            UpdatedAt = new DateTime(2022, 12, 22, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 12, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "test2@example.com",
                            FullName = "Test User Two",
                            PasswordHash = "fbb4a8a163ffa958b4f02bf9cabb30cfefb40de803f2c4c346a9d39b3be1b544",
                            Role = "Customer",
                            UpdatedAt = new DateTime(2022, 12, 27, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FitVerse.Web.Models.CartItem", b =>
                {
                    b.HasOne("FitVerse.Web.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitVerse.Web.Models.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitVerse.Web.Models.Category", b =>
                {
                    b.HasOne("FitVerse.Web.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("FitVerse.Web.Models.Order", b =>
                {
                    b.HasOne("FitVerse.Web.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitVerse.Web.Models.OrderItem", b =>
                {
                    b.HasOne("FitVerse.Web.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitVerse.Web.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FitVerse.Web.Models.Product", b =>
                {
                    b.HasOne("FitVerse.Web.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FitVerse.Web.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("FitVerse.Web.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("FitVerse.Web.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("FitVerse.Web.Models.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
