<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Views\Cart\**" />
    <Compile Remove="Views\Order\**" />
    <Compile Remove="Views\ProductDetails\**" />
    <Content Remove="Views\Cart\**" />
    <Content Remove="Views\Order\**" />
    <Content Remove="Views\ProductDetails\**" />
    <EmbeddedResource Remove="Views\Cart\**" />
    <EmbeddedResource Remove="Views\Order\**" />
    <EmbeddedResource Remove="Views\ProductDetails\**" />
    <None Remove="Views\Cart\**" />
    <None Remove="Views\Order\**" />
    <None Remove="Views\ProductDetails\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ViewModels\Cart\" />
    <Folder Include="ViewModels\Account\" />
    <Folder Include="ViewModels\Order\" />
    <Folder Include="ViewModels\Home\" />
    <Folder Include="Views\Product\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="9.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.Session" Version="2.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="9.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
  </ItemGroup>

</Project>
